version: "3.9"

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "5000:5000"
    env_file:
      - ./auth_service/.env
    depends_on:
      - auth_db
    volumes:
      - ./auth_service:/app

  course_service:
    build: ./course_service
    container_name: course_service
    ports:
      - "5001:5001"
    env_file:
      - ./course_service/.env
    depends_on:
      - course_db
    volumes:
      - ./course_service:/app

  auth_db:
    image: postgres:14
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_volume:/var/lib/postgresql/data

  course_db:
    image: postgres:14
    container_name: course_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: course_db
    ports:
      - "5434:5432"
    volumes:
      - course_db_volume:/var/lib/postgresql/data

  nginx:
    build: ./nginx_gateway
    container_name: nginx_gateway
    ports:
      - "8000:80"
    depends_on:
      - auth_service
      - course_service
    volumes:
      - ./nginx_gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  auth_db_volume:
  course_db_volume:
